name: build-dist
on: [push: branches: [main]]

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Install Dependancies
        run: |
          apt-get install git
          apt-get install automake
          apt-get install gcc
      - name: Step 2 - Build Project
        - run: |
          git clone https://github.com/w1wwwwww/hellognu
          cd hellognu
          autoreconf --install
          ./configure
          make distcheck
      - name: Step 3 - Upload Artifacts
        run: tar xzf hellognu-1.0.0.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: hellognu-${{ github.run_attempt }}
          path: hellognu-1.0.0
