name: build-dist
on: [push]

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Build Project
        run: |
          git clone https://github.com/w1wwwwww/hellognu
          cd hellognu
          autoreconf --install
          ./configure
          make distcheck
          tar xzf hellognu-1.0.0.tar.gz
      - name: Step 2 - Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hellognu-${{ github.run_attempt }}
          path: hellognu-1.0.0.tar.gz
